"""Added themes

Revision ID: d563e601a000
Revises: 3cda98c078a3
Create Date: 2024-05-11 20:59:03.229283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd563e601a000'
down_revision: Union[str, None] = '3cda98c078a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('themes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('active_date', sa.Date(), nullable=False),
    sa.Column('main', sa.String(), nullable=False),
    sa.Column('all', sa.String(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('attempts', sa.Column('theme_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'attempts', 'themes', ['theme_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'attempts', type_='foreignkey')
    op.drop_column('attempts', 'theme_id')
    op.drop_table('themes')
    # ### end Alembic commands ###
